[general]
title = "Leben, Träumen und Sterben"
subtitle = "kurze Geschichten rund ums Jahr"
author = "Josa Wode"
language = "de" #de, en, ...

[latex]
bookPrint = "true" #true, false #create document for book printing, allow preliminaries and appendix (directories: latex/bookPreliminaries and latex/bookAppendix)
tableOfContents = "true" #true, false
isbn = "xxx-x-xxxx-xxxx-x"
pageFormat = "a5" #a0 - a6, b0 - b6 #define page size
#pageWidth = "210mm" #only when not using pageFormat
#pageHeight = "297mm" #only when not using pageFormat
bindingOffset = "15mm" #part of the page that is lost in binding
fontSize = "10" #e.g. 11 12.5 #in pt
printAuthorOnTitle = "false" #true, false #determines if title page begins with author name
#title = "" #comment out if same as general.title
#subtitle = "Eine Geschichte von Josa Wode" #comment out if same as general.subtitle
#halfTitle = "" #half title for book printing #comment out if same as title
pdfsubject = "Geschichte"
pdfkeywords = "geschichte, alte, josa, wode"
hascolorlinks = "false"
urlcolor = "blue"
linkcolor = "black"
    
[html]
#title = "" #comment out if same as general.title
#subtitle = "" #comment out if same as general.subtitle
headertitle = "Kommt und holt sie | eine Geschichte von Josa Wode"
url = "http://writing.fotoelectrics.de/documents/come-get-her/de/html/" #meta property og:url
metadescription = "Eine kurze Geschichte von Josa Wode - Es könnte ein Märchen sein, wenn es sich benehmen würde. (Lizenz: Creative Commons BY-NC-SA 3.0)"    #meta description and meta property og:description
locale = "de_DE" #de_DE, en_GB, ... #meta property og:locale
sitename = "writing.fotoelectrics" #meta property og:site_name
#previewimage = "" #meta property og:image #comment out for no image tag
